services:
  mysql:
    image: mysql:8.0
    container_name: hr-mysql-dev
    environment:
      MYSQL_ROOT_PASSWORD: root_password_dev
      MYSQL_DATABASE: hr_database
      MYSQL_USER: hr_user
      MYSQL_PASSWORD: hr_password_dev_123
    ports:
      - "3306:3306"
    volumes:
      - mysql_data_dev:/var/lib/mysql
    networks:
      - hr-network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "hr_user", "-phr_password_dev_123"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s
    command: --default-authentication-plugin=mysql_native_password

  app:
    build:
      context: .
      target: development
    container_name: hr-backend-dev
    ports:
      - "3000:3000"
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
      - PORT=3000
      - DB_TYPE=mysql
      - DB_HOST=mysql
      - DB_PORT=3306
      - DB_USERNAME=hr_user
      - DB_PASSWORD=hr_password_dev_123
      - DB_DATABASE=hr_database
      - DB_SYNCHRONIZE=false
      - DB_LOGGING=true
    command: pnpm run start:dev
    depends_on:
      mysql:
        condition: service_healthy
    networks:
      - hr-network

volumes:
  mysql_data_dev:
    driver: local

networks:
  hr-network:
    driver: bridge
